Azo shop
gokulwebdeveloper/POC-Autozone pull request #12
Opened 2020-06-24 13:52 UTC by LydiaLilly

Shop page implemented

2020-06-24 14:47 UTC, gopalprathi commented
Fix reference errors and test errors. And please rebase all commits in one.

2020-06-25 08:31 UTC, LydiaLilly commented
Fix reference errors and test errors. And please rebase all commits in one. - done.  Please merge the pull request

2020-06-25 08:48 UTC, gokulwebdeveloper requested changes
Please fix this issue @LydiaAtos @LydiaLilly @manikandanatos @ManikandanS910

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Brand/Brand.test.js
> +					"Mango",
@LydiaAtos @LydiaLilly I see some code indentation issue. Please align fix it.

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Catagory/Catagory.js
> +           {console.log("list value " + JSON.stringify( props.data.items) )}
remove this console log

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Catagory/Catagory.js
> +
add props type validation

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/ColorBox/ColorBox.js
> +
Please add props type and default props validation

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/ListItem/ListItem.js
> +                console.log("item value " +item );
remove console log

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Pagination/PageItem.js
> +                console.log("item value " +item );
remove console log

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Pagination/Pagination.js
> +
remove all console log and add props validation

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/Shops.js
> +					"Mango",
Align the code properly

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/index.html
> +    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
remove this code

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
dont include jquery file directly in index,html, kindly include it as module

2020-06-25 08:48 UTC, gokulwebdeveloper commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
remove this

2020-06-25 08:48 UTC, gokulwebdeveloper commented
Please rebase your commit

2020-06-25 08:50 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/ListItem/ListItem.js
> +                console.log("item value " +item );
add props and default props validation

2020-06-25 09:52 UTC, LydiaLilly commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
this is needed for jquery range slider component. so cant remove it.

2020-06-25 09:53 UTC, LydiaLilly commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
if i include only in module jquery element is not working.

2020-06-25 09:53 UTC, LydiaLilly commented on autozone-poc/src/index.html
> +    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
need for jquery element

2020-06-25 12:12 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Brand/Brand.test.js
> +					"Mango",
done

2020-06-25 12:12 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Catagory/Catagory.js
> +           {console.log("list value " + JSON.stringify( props.data.items) )}
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Catagory/Catagory.js
> +
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Catagory/Catagory.js
> +
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/ColorBox/ColorBox.js
> +
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/ListItem/ListItem.js
> +                console.log("item value " +item );
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Pagination/Pagination.js
> +
done

2020-06-25 12:13 UTC, LydiaLilly commented on autozone-poc/src/components/Shops/Shops.js
> +					"Mango",
done

2020-06-25 12:15 UTC, LydiaLilly commented
Hi Gokul, implemented and replied for review comments. Please check. Once you resolve all comments I will do rebase.

2020-06-25 16:09 UTC, gopalprathi commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
install jquery like "npm i jquery"  and then you can include in module like "import $ from jquery" it will work.

2020-06-25 16:09 UTC, gopalprathi commented on autozone-poc/src/index.html
> +    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
install jquery like "npm i jquery"  and then you can include in module like "import $ from jquery" it will work.

2020-06-25 16:09 UTC, gopalprathi commented
install jquery like "npm i jquery"  and then you can include in module like "import $ from jquery" it will work.

2020-06-26 05:44 UTC, gokulwebdeveloper commented on autozone-poc/src/index.html
> +    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
you can handle by installing jquery in node module and logic in   componentdidmount or useEffect method.

2020-06-26 05:44 UTC, gokulwebdeveloper commented
Still i see 53 commit @LydiaAtos, please rebase it

2020-06-26 14:05 UTC, LydiaLilly commented
rebased to one commit, slider(removed jquery from index.html) and pagination is included. Please merge the pull request. @gokulwebdeveloper

2020-06-28 10:22 UTC, gokulwebdeveloper approved these changes

2020-06-28 10:22 UTC, merged