Azo home page
gokulwebdeveloper/POC-Autozone pull request #16
Opened 2020-06-26 10:15 UTC by kumarkp

2020-06-28 10:20 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Home.js
> +Home.propTypes = {
add props validation and default props

2020-06-28 10:20 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Home.js
> +              <TopCatagoryArea topCatagoryAreaText="Clothing" style={bgImgTopCatArea1} />
instead of using multiple time please make it single time usage and pass the value as props

2020-06-28 10:20 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Home.js
> +            <img src='src/utlis/img/core-img/brand1.png' alt=""/>
Why this is statically implemented

2020-06-28 10:20 UTC, gokulwebdeveloper commented on autozone-poc/src/utlis/slick_slider/SimpleSlider.js
> +export default class SimpleSlider extends Component {
Why don't use functional component instead of class component

2020-06-29 08:04 UTC, kumarkp commented on autozone-poc/src/utlis/slick_slider/SimpleSlider.js
> +export default class SimpleSlider extends Component {
Class component has been changed onto function component

2020-06-29 08:05 UTC, kumarkp commented on autozone-poc/src/components/Home.js
> +            <img src='src/utlis/img/core-img/brand1.png' alt=""/>
Component data implemented has dynamically

2020-06-29 08:06 UTC, kumarkp commented on autozone-poc/src/components/Home.js
> +Home.propTypes = {
Added props and default props

2020-06-29 08:06 UTC, kumarkp commented on autozone-poc/src/components/Home.js
> +              <TopCatagoryArea topCatagoryAreaText="Clothing" style={bgImgTopCatArea1} />
Changed into single by using props

2020-06-29 11:55 UTC, gokulwebdeveloper requested changes
I see all components on your branch. @gopalprathi  Please review again,

2020-06-29 11:55 UTC, gokulwebdeveloper commented on autozone-poc/src/components/CheckoutPage/CheckoutPage.js
> +import $ from 'jquery';
move above the css files

2020-06-29 11:55 UTC, gokulwebdeveloper commented on autozone-poc/src/components/CheckoutPage/CheckoutPage.js
> +  $(document).ready(function(){
Please implement state validation

2020-06-29 11:55 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Home.js
> +            <img src='src/utlis/img/core-img/brand1.png' alt=""/>
I dont see any update in the code

2020-06-30 02:49 UTC, closed without merging

2020-06-30 02:49 UTC, kumarkp commented
duplicate