signin and signup with api
gokulwebdeveloper/POC-Autozone pull request #21
Opened 2020-06-29 10:35 UTC by Asifrizwan6989

Signin and Signup page created, Api connection working fine

Server-side url: https://github.com/Asifrizwan6989/AutoZoneServer.git

2020-06-29 11:02 UTC, gokulwebdeveloper requested changes
Where is the unit test case

2020-06-29 11:02 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Signin/Signin.js
> +              <input className="form-control" type="email" name="emailid" id="emailid" placeholder="Enter email id" ref={register({required:true})}/>
Please discuss with Gopal and resuse the input field component

2020-07-01 05:07 UTC, Asifrizwan6989 commented on autozone-poc/src/components/Signin/Signin.js
> +              <input className="form-control" type="email" name="emailid" id="emailid" placeholder="Enter email id" ref={register({required:true})}/>
implemented and push in second commit

2020-07-02 06:55 UTC, gopalprathi commented
@Asifrizwan6989 Resolve conflicts

2020-07-02 09:05 UTC, gokulwebdeveloper commented
Please resolve the conflicts in the branch

2020-07-09 15:04 UTC, Asifrizwan6989 commented
changes done in signin and signup pull request

2020-07-09 15:04 UTC, closed without merging