Added pagination for local JSON and removed axios dummy URl calls
gokulwebdeveloper/POC-Autozone pull request #22
Opened 2020-06-29 11:09 UTC by ManikandanS910

2020-06-29 12:00 UTC, gokulwebdeveloper requested changes

2020-06-29 12:00 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/product-list/ProductList.js
> -        axios
Please make as reuseable code. Try to implement as possibility usecase

2020-06-29 12:00 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/product-list/ProductList.js
>  import Product from './Product.js';
It is possible to convert into functional component. Also, add props validation in the page.

2020-06-29 12:00 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Shops/product-list/ProductList.js
> -// import React, { Fragment } from 'react';
Remove this unused code

2020-06-29 15:45 UTC, ManikandanS910 commented on autozone-poc/src/components/Shops/product-list/ProductList.js
> -// import React, { Fragment } from 'react';
Already removed code

2020-06-30 08:04 UTC, ManikandanS910 commented on autozone-poc/src/components/Shops/product-list/ProductList.js
>  import Product from './Product.js';
Changed to functional component

2020-06-30 08:05 UTC, ManikandanS910 commented on autozone-poc/src/components/Shops/product-list/ProductList.js
> -        axios
commented on removed code

2020-06-30 12:44 UTC, gokulwebdeveloper approved these changes
Please remove commented line while you integrating redux

2020-06-30 15:54 UTC, merged