Implemented Json data for blog
gokulwebdeveloper/POC-Autozone pull request #33
Opened 2020-07-06 09:09 UTC by Sowmiya89

merge request

2020-07-06 10:17 UTC, gokulwebdeveloper requested changes

2020-07-06 10:17 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Blog/Blog.js
> +            "https://www.autozone.com/diy/wp-content/uploads/2020/04/is-my-car-battery-dead-1024x683.jpg" +
Why it is hard coded

2020-07-06 10:17 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Blog/Blog.js
> +import list from "../Blog/blog.json";
kindly use axios call or fetch call to implement to use the article in the page

2020-07-06 14:25 UTC, Sowmiya89 commented on autozone-poc/src/components/Blog/Blog.js
> +            "https://www.autozone.com/diy/wp-content/uploads/2020/04/is-my-car-battery-dead-1024x683.jpg" +
Fixed

2020-07-06 14:26 UTC, Sowmiya89 commented on autozone-poc/src/components/Blog/Blog.js
> +import list from "../Blog/blog.json";
Added axios call

2020-07-07 05:15 UTC, gokulwebdeveloper approved these changes

2020-07-07 05:16 UTC, gokulwebdeveloper commented
Please resolve conflict and let me know so that I will merge

2020-07-09 05:16 UTC, merged