Added About AutoZone, Investor Information and Affiliate Program Page. And resolved conflicts.
gokulwebdeveloper/POC-Autozone pull request #35
Opened 2020-07-06 15:55 UTC by A737962

Please review this PR.

2020-07-07 05:20 UTC, gokulwebdeveloper requested changes

2020-07-07 05:20 UTC, gokulwebdeveloper commented on autozone-poc/src/components/AboutUs/MockData/Mock.json
> +        },
remove all external site files. copy paste in our website

2020-07-07 05:20 UTC, gokulwebdeveloper commented on autozone-poc/src/components/AboutUs/MockData/Mock.json
> +            "content": "<div class=\"container-fluid\"><div class=\"row\"><div class=\"w-100\"><img class=\"float-right\" src=\"https:\/\/www.autozone.com\/company\/images\/investor_relations\/IR_log
Remove slash and use that in our json. Also remove unwanted CSS class

2020-07-07 05:20 UTC, gokulwebdeveloper commented on autozone-poc/src/utlis/navigation/menu/Menu.js
> +                  <NavLink to="/aboutAutozone">About AutoZone</NavLink>
Use extact to avoid URL confusion.

2020-07-16 05:17 UTC, A737962 commented
Please review. And all the commits are different in nature. Please merge it as it is.

2020-07-24 05:41 UTC, closed without merging