completed filter and sorting for list of products
gokulwebdeveloper/POC-Autozone pull request #36
Opened 2020-07-09 08:00 UTC by ManikandanS910

2020-07-09 09:12 UTC, gokulwebdeveloper requested changes

2020-07-09 09:12 UTC, gokulwebdeveloper commented on autozone-poc/src/Redux/reducers/productFilterReducer.js
> +            console.log("action type inside: " + action.type);
remove console.log

2020-07-09 09:12 UTC, gokulwebdeveloper commented on autozone-poc/src/Redux/reducers/productSortReducer.js
> +            console.log("action type inside: " + JSON.stringify(action.payload.sortType));
remove all console.log from your files

2020-07-09 09:12 UTC, gokulwebdeveloper commented on autozone-poc/src/components/ProductDetails/DetailsSection.js
> +                    <div key={index}><img src={image} alt="" /></div>
try to add product name for alt tag

2020-07-09 11:35 UTC, ManikandanS910 commented on autozone-poc/src/Redux/reducers/productFilterReducer.js
> +            console.log("action type inside: " + action.type);
Removed

2020-07-09 11:35 UTC, ManikandanS910 commented on autozone-poc/src/Redux/reducers/productSortReducer.js
> +            console.log("action type inside: " + JSON.stringify(action.payload.sortType));
Removed logs

2020-07-09 11:36 UTC, ManikandanS910 commented on autozone-poc/src/components/ProductDetails/DetailsSection.js
> +                    <div key={index}><img src={image} alt="" /></div>
Added product name for alt attribute

2020-07-13 05:48 UTC, gokulwebdeveloper requested changes

2020-07-13 05:48 UTC, gokulwebdeveloper commented on autozone-poc/src/utlis/clickAction/clickAction.js
> +            //this.props.filterProducts(props.productData);
can you remove commented lines

2020-07-13 09:27 UTC, ManikandanS910 commented on autozone-poc/src/utlis/clickAction/clickAction.js
> +            //this.props.filterProducts(props.productData);
Removed this unused file

2020-07-13 14:31 UTC, merged