signin and signup
gokulwebdeveloper/POC-Autozone pull request #38
Opened 2020-07-09 14:29 UTC by Asifrizwan6989

Signin and signup pages

2020-07-13 05:45 UTC, gokulwebdeveloper requested changes

2020-07-13 05:45 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Signin/Signin.js
> +      console.log(response);
remove console.log

2020-07-13 05:45 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Signin/Signin.js
> +      window.location.assign("/");
can you use a router redirect

2020-07-13 05:45 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Signup/Signup.js
> +  $(document).ready(function(){
remove jquery validation and implement state-based validation in react

2020-07-13 05:45 UTC, gokulwebdeveloper commented on autozone-poc/src/components/Signup/Signup.js
> +    axios.post("http://localhost:5000/user/signup", data).then((response) => {
dont use hard-coded links

2020-07-13 12:19 UTC, Asifrizwan6989 commented on autozone-poc/src/components/Signup/Signup.js
> +  $(document).ready(function(){
Validation already written in j-query for reusable component, that why i written in j-query to achieve scenario

2020-07-13 13:45 UTC, Asifrizwan6989 commented on autozone-poc/src/components/Signup/Signup.js
> +    axios.post("http://localhost:5000/user/signup", data).then((response) => {
the code will work with that url:http://localhost:5000/user/signup

2020-07-13 16:06 UTC, Asifrizwan6989 commented on autozone-poc/src/components/Signin/Signin.js
> +      console.log(response);
removed

2020-07-13 16:08 UTC, Asifrizwan6989 commented on autozone-poc/src/components/Signin/Signin.js
> +      window.location.assign("/");
i will implement in next version

2020-07-14 08:54 UTC, gokulwebdeveloper approved these changes

2020-07-14 08:55 UTC, merged